---
- name: Converge
  hosts: all
  become: yes
  vars:
    falcon_client_id: "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
    falcon_client_secret: "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
  roles:
    - role: crowdstrike.falcon.falcon_configure
      vars:
        falcon_option_set: yes
        falcon_cid: "{{ lookup('env', 'FALCON_CID') }}"
        falcon_provisioning_token: '12345678'
        falcon_tags: 'falcon,example,tags'
        falcon_billing: 'metered'
        falcon_message_log: yes
        falcon_backend: 'kernel'
        falcon_feature:
          - enableLog
          - disableLogBuffer
