---
- name: Converge
  hosts: all
  become: yes
  vars:
    falcon_client_id: "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
    falcon_client_secret: "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
  roles:
    - role: crowdstrike.falcon.falcon_install
