---
# tasks file for falcon_installation
- block:
  - include_tasks: uninstall.yml
  when: falcon_uninstall
  become: true
  become_user: root

- block:
    - include_tasks: preinstall.yml
  when:
    - not falcon_uninstall

- block:
  - include_tasks: url.yml
  when:
    - not falcon_uninstall
    - falcon_install_method == "url"

- block:
  - include_tasks: api.yml
  when:
    - not falcon_uninstall
    - falcon_install_method == "api"

- block:
  - include_tasks: install.yml
  when:
    - not falcon_uninstall
  become: true
  become_user: root
