---
- name: Prepare
  hosts: all
  vars:
    windows_install_args: "/norestart GROUPING_TAGS=molecule,testing"
  tasks:
    - name: Set ProvToken info (if applicable)
      ansible.builtin.set_fact:
        windows_install_args: "{{ windows_install_args }} ProvToken={{ lookup('env', 'FALCON_PROV_TOKEN') }}"
      when: lookup('env', 'FALCON_PROV_TOKEN')

    - name: Install Falcon Sensor
      ansible.builtin.include_role:
        name: crowdstrike.falcon.falcon_install
      vars:
        falcon_client_id: "{{ lookup('env', 'FALCON_CLIENT_ID') }}"
        falcon_client_secret: "{{ lookup('env', 'FALCON_CLIENT_SECRET') }}"
        falcon_windows_install_args: "{{ windows_install_args }}"
