---
- name: Prepare
  hosts: all
  become: yes
  tasks:
    # Ubuntu specific
    - name: Install apt dependencies
      apt:
        name:
          - gpg-agent
        update_cache: yes
      ignore_errors: yes
      when: ansible_facts['pkg_mgr'] == 'apt'

    - name: Install dependencies
      package:
        name:
          - sudo
        state: present
