- name: CrowdStrike Falcon | Remove Downloaded Sensor Installation directory (local)
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  changed_when: false
  delegate_to: localhost
  loop:
    - "{{ falcon_sensor_download.path }}"
    - "{{ falcon_sensor_download.path + '.lock' }}"
  when: falcon_api_sensor_download_cleanup
