---
# Tasks for Installing CrowdStrike's Falcon Sensor via URL
- name: CrowdStrike Falcon | Downloading Installation Package from URL
  ansible.builtin.get_url:
    url: "{{ falcon_download_url }}"
    dest: "{{ falcon_install_temp_directory.path }}"
    url_username: "{{ falcon_download_url_username | default(omit) }}"
    url_password: "{{ falcon_download_url_password | default(omit) }}"
    mode: 0640
  when:
    - falcon_download_url | default('', true) | length > 0
    - falcon_install_temp_directory | default('', true) | length > 0
  register: falcon_sensor_download
  retries: "{{ falcon_retries }}"
  delay: "{{ falcon_delay }}"
  until: falcon_sensor_download is success

- name: CrowdStrike Falcon | Set full file download path
  ansible.builtin.set_fact:
    falcon_sensor_pkg: "{{ falcon_sensor_download.dest }}"
