---
# This task file validates CrowdStrike Falcon API credentials
# It can be included by any role that needs to perform API operations
# Usage: include_tasks: validate_api_credentials.yml

- name: "CrowdStrike Falcon | Validate Required API URL Is Defined"
  ansible.builtin.assert:
    that:
      - falcon_cloud | default('', true) | length > 0
    fail_msg: "falcon_cloud is not configured! Please configure falcon_cloud and re-run again!"
    success_msg: "falcon_cloud is properly configured."

- name: "CrowdStrike Falcon | Validate CrowdStrike API Client ID Is Defined"
  ansible.builtin.assert:
    that:
      - falcon_client_id | default('', true) | length > 0
    fail_msg: "falcon_client_id is not configured! Please configure falcon_client_id and re-run again!"
    success_msg: "falcon_client_id is properly configured."

- name: "CrowdStrike Falcon | Validate CrowdStrike API Client Secret Is Defined"
  ansible.builtin.assert:
    that:
      - falcon_client_secret | default('', true) | length > 0
    fail_msg: "falcon_client_secret is not configured! Please configure falcon_client_secret and re-run again!"
    success_msg: "falcon_client_secret is properly configured."
