---
# Block when falcon_sensor_update_policy_name is supplied
- name: Sensor Update Policy Block
  when: falcon_sensor_update_policy_name
  block:
    - name: "CrowdStrike Falcon | Build Sensor Update Policy API Query"
      ansible.builtin.set_fact:
        falcon_sensor_update_policy_query: "{{ 'platform_name:\"' + falcon_sensor_update_policy_platform + '\"+name.raw:\"' + falcon_sensor_update_policy_name + '\"' }}"

    - name: "CrowdStrike Falcon | Search for Sensor Update Policy"
      ansible.windows.win_uri:
        url: "https://{{ falcon_cloud }}/policy/combined/sensor-update/v2?filter={{ falcon_sensor_update_policy_query | urlencode }}"
        method: GET
        return_content: true
        headers:
          authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
          Content-Type: application/json
      register: falcon_sensor_update_policy_info
      no_log: "{{ falcon_api_enable_no_log }}"
      run_once: "{{ falcon_sensor_update_policy_run_once }}"

    - name: "CrowdStrike Falcon | Validate Sensor Update Policy request"
      ansible.builtin.fail:
        msg: "No Falcon Sensor Update Policy with name: {{ falcon_sensor_update_policy_name }} was found!"
      when: falcon_sensor_update_policy_info.json.resources[0] is not defined

    - name: "CrowdStrike Falcon | Get the Falcon Sensor version from Update Policy"
      ansible.builtin.set_fact:
        falcon_sensor_update_policy_package_version: "{{ falcon_sensor_update_policy_info.json.resources[0].settings.sensor_version }}"

    - name: "CrowdStrike Falcon | Build API Sensor Query based on Sensor Update Policy"
      ansible.builtin.set_fact:
        falcon_os_query: "{{ 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"+version:\"' + falcon_sensor_update_policy_package_version + '\"' }}"

- name: "CrowdStrike Falcon | Build API Sensor Query"
  ansible.builtin.set_fact:
    falcon_os_query: "{{ 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"+version:\"' + falcon_sensor_version + '\"'
      if (falcon_sensor_version) else 'os:\"' + falcon_target_os + '\"+os_version:\"' + falcon_os_version + '\"' }}"
  when: not falcon_sensor_update_policy_name

- name: CrowdStrike Falcon | Get list of filtered Falcon sensors
  ansible.windows.win_uri:
    url: "https://{{ falcon_cloud }}/sensors/combined/installers/v1?sort=version|desc&filter={{ falcon_os_query | urlencode }}"
    method: GET
    return_content: true
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
      Content-Type: application/json
  register: falcon_api_installer_list
  no_log: "{{ falcon_api_enable_no_log }}"

- name: CrowdStrike Falcon | Validate Sensor request
  ansible.builtin.fail:
    msg: "No Falcon Sensor was found! If passing in falcon_sensor_version, ensure it is correct!"
  when: falcon_api_installer_list.json.resources[0] is not defined

- name: CrowdStrike Falcon | Download Falcon Sensor Installation Package
  ansible.windows.win_get_url:
    url: "https://{{ falcon_cloud }}/sensors/entities/download-installer/v1?id={{ falcon_api_installer_list.json.resources[falcon_sensor_version_decrement | int].sha256 }}"
    dest: "{{ falcon_install_win_temp_directory.path }}\\{{ falcon_api_installer_list.json.resources[falcon_sensor_version_decrement | int].name }}"
    checksum: "{{ falcon_api_installer_list.json.resources[falcon_sensor_version_decrement | int].sha256 }}"
    checksum_algorithm: sha256
    headers:
      authorization: "Bearer {{ falcon_api_oauth2_token.json.access_token }}"
  changed_when: false
  register: falcon_sensor_download
  no_log: "{{ falcon_api_enable_no_log }}"

- name: CrowdStrike Falcon | Set full file download path
  ansible.builtin.set_fact:
    falcon_sensor_pkg: "{{ falcon_sensor_download.dest }}"
