---
# vars file for falcon_install
linux_packagers: "{{ rpm_packagers + dpkg_packagers }}"

rpm_packagers:
  - yum
  - rpm
  - dnf
  - zypper

dpkg_packagers:
  - apt

falcon_gpg_key: falcon-sensor.gpg

falcon_cloud_urls:
  us-1: "api.crowdstrike.com"
  us-2: "api.us-2.crowdstrike.com"
  eu-1: "api.eu-1.crowdstrike.com"
  us-gov-1: "api.laggar.gcw.crowdstrike.com"

falcon_os_arch_dict:
  # exclude arm64 and s390x
  x86_64: "\"+os_version:!~\"arm64\"+os_version:!~\"zLinux\""
  aarch64: "\"+os_version:~\"arm64\""
  s390x: "\"+os_version:~\"zLinux\""
