---
# handlers file for falcon_configure
  - name: CrowdStrike Falcon | Restart Falcon Sensor
    ansible.builtin.service:
      name: falcon-sensor
      state: restarted
    when: info.falconctl_info.cid
