---
- name: Simple Falcon Event Stream Usage Example
  hosts: all
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ FALCON_CLIENT_ID }}"
        falcon_client_secret: "{{ FALCON_CLIENT_SECRET }}"
        falcon_cloud: "us-2"
        stream_name: "eda-example"
        # delay: 0
        include_event_types:
          - "DetectionSummaryEvent"

  rules:
    - name: print output
      condition: event.falcon is defined
      action:
        debug:
