---
- name: Simple Falcon Event Stream Usage Example
  hosts: all
  sources:
    - crowdstrike.falcon.eventstream:
        falcon_client_id: "{{ FALCON_CLIENT_ID }}"
        falcon_client_secret: "{{ FALCON_CLIENT_SECRET }}"
        falcon_cloud: "us-2"
        # offset: 12345
        stream_name: "eda-example"
        include_event_types:
          - "DetectionSummaryEvent"

  rules:
    - name: Print High and Critical Severity Detection Events
      condition: event.falcon.event.Severity > 3
      action:
        debug:
