name: "falcon_install"
on:
  schedule:
    - cron: '0 6 * * *'
  push:
    paths:
      - 'roles/falcon_install/**'
      - 'molecule/falcon_install/**'
      - '.github/workflows/falcon_install.yml'
  pull_request_target:
    types: [ labeled ]
    paths:
      - 'roles/falcon_install/**'
      - 'molecule/falcon_install/**'
      - '.github/workflows/falcon_install.yml'
jobs:
  molecule:
    if: |
      github.event_name == 'push' ||
      github.event_name == 'schedule' ||
      (github.event_name == 'pull_request_target' &&
      github.event.label.name == 'ok-to-test')
    runs-on: ubuntu-18.04
    env:
      PY_COLORS: 1
      ANSIBLE_FORCE_COLOR: 1
      FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
      FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          - { "distro":"centos7" }
          - { "distro":"rockylinux8" }
          - { "distro":"ubuntu2004" }
        collection_role:
          - falcon_install
    steps:
      - name: Check out code
        uses: actions/checkout@v2
        if: github.event_name != 'pull_request_target'

      - name: Check out code
        uses: actions/checkout@v2
        with:
          ref: ${{github.event.pull_request.head.sha}}
        if: github.event_name == 'pull_request_target'

      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install dependencies
        run: |
          sudo apt install apt-transport-https ca-certificates curl software-properties-common
          python -m pip install --upgrade pip
          pip install molecule[docker,lint,ansible] ansible yamllint ansible-lint==5.4.0

      - name: Build/Install the collection
        run: |
          collection_file=$( basename $(ansible-galaxy collection build -f | awk -F" " '{print $NF}'))
          ansible-galaxy collection install $collection_file

      - name: Run role tests
        run: >-
          molecule --version &&
          ansible --version &&
          MOLECULE_DISTRO=${{ matrix.molecule_distro.distro }}
          molecule --debug test -s ${{ matrix.collection_role }} -- -v -e "falcon_skip_kernel_compat_check=yes"
